spring.application.name=hermes

#postgresql config
spring.datasource.url= jdbc:postgresql://localhost:5432/athenaeum
spring.datasource.username =postgres
spring.datasource.password =root

#hibernate config
spring.jpa.hibernate.ddl-auto=update

# SMTP server configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kichuakshay290@gmail.com
spring.mail.password=ooyi etdf pxfh tmdm
spring.mail.protocol=smtp
spring.mail.smtp.auth=true
spring.mail.smtp.starttls.enable=true
spring.mail.smtp.ssl.trust=smtp.gmail.com

otp.expiration.time = 1

