spring.application.name=hermes

#postgresql config
spring.datasource.url= jdbc:postgresql://localhost:5432/athenaeum
spring.datasource.username =postgres
spring.datasource.password =root

#hibernate config
spring.jpa.hibernate.ddl-auto=update

# SMTP Server Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=imageannotations32@gmail.com
spring.mail.password=jpej bpgr qadf lkxz

# SMTP Protocol and Authentication
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Additional Security Properties
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Timeout Configuration
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Debug Logging
spring.mail.properties.mail.debug=true

#security
logging.level.org.springframework.security=DEBUG
otp.expiration.time = 1
signkey = 657657628762887e6dgecfdc6xq5fe67fdyugdvrysfcxvwtye27u6gdb7yubw7ysvtyww

server.port = 8081

