spring.application.name=hermes

#postgresql config
spring.datasource.url= jdbc:postgresql://localhost:5432/athenaeum
spring.datasource.username =postgres
spring.datasource.password =root

#hibernate config
spring.jpa.hibernate.ddl-auto=update

